<p>Il jazz è una forma musicale contemporanea, di cui l'improvvisazione  costituisce la caratteristica fondamentale. Nato nei primi anni del XX secolo  nelle comunità afroamericane del sud degli Stati Uniti, è frutto di una  confluenza di tradizioni musicali africane ed europee. Oltre  all'improvvisazione, le sue caratteristiche peculiari sono il ritmo swing  spesso sincopato, la poliritmia ed il tono malinconico dell'uso delle blue  note.<br>
  Nel jazz ci sono due forme primarie: il blues, in 12 battute, e la canzone,  in 32 battute. L'essenza dell'improvvisazione è nella linea melodica, ciò è  dovuto al fatto che il mezzo jazz prototipico (originale) è il gruppo di ottoni,  in cui, dato che ogni suonatore può produrre una sola nota alla volta, gli  assolo sono necessariamente melodici. Il pianoforte venne dopo, copiando però  le caratteristiche dell'insieme di ottoni. <br>
  Sin dai primi tempi il jazz ha incorporato nel suo linguaggio i generi della  musica popolare americana, dal ragtime, al blues, alla musica leggera e colta  dei grandi compositori americani.<br>
  In tempi più recenti il jazz si è mescolato con tutti i generi musicali  moderni anche non statunitensi, come il samba, la musica caraibica e il rock.<br>
  Il jazz si è trasformato, nel corso di tutto il XX secolo, evolvendosi in  una gran varietà di stili e sottogeneri: dal dixieland di New Orleans dei primi  anni, allo swing delle big bands negli anni trenta e quaranta, dal bebop della  seconda metà degli anni quaranta, al cool jazz e al hard bop degli anni  cinquanta, dal free jazz degli anni sessanta alla fusion degli anni settanta,  fino alle contaminazioni con il funk e l'hip hop dei decenni successivi.</p>
  
<p><h2>Caratteristiche  principali</h2>
  Il jazz si sviluppa agli inizi del XX secolo a New Orleans,Louisiana.La  cittadina costituiva un ribollente crogiolo etnico:prima di dominazione  francese,poi spagnola,era diventata parte degli Stati Uniti con il  &quot;Louisiana Purchase&quot; del 1803. Il jazz si afferma subito come sintesi  tra numerose culture musicali, europee (musica per banda militare, canti da  chiesa, opera lirica) e africane (percussione, ritmo). Secondo il critico  musicale classico Giulio Confalonieri, il jazz è stata la musica più vitale,  libera e rappresentativa dell'epoca contemporanea.<br>
  Dal punto di vista tecnico, il jazz moderno è caratterizzato dall'uso  estensivo dell'improvvisazione, di blue note, di poliritmie e di progressioni  armoniche insolite se confrontate con quelle in uso nella musica classica. In  particolare la pulsazione ritmica jazzistica, elastica e a volte scandita in  maniera ineguale, chiamata swing, ha sempre rivestito grande importanza in  quasi tutte le forme di questa musica.<br>
  Sin dagli inizi, l'interpretazione del genere ha posto un grande accento  sull'espressività e, nel corso degli anni, anche sul virtuosismo strumentale.  La musica jazz degli albori era basata su combinazioni di elementi musicali  africani, articolata cioè su scale pentatoniche, con caratteristiche blue notes,  mescolate ad armonie derivate dalla musica colta europea, ed un notevole uso di  ritmi sincopati, e di poliritmi musica colta e jazz si sono costantemente  avvicinate al punto che non è raro assistere a performance classiche di  musicisti jazz e performance jazz di musicisti classici.[evasivo]<br>
  Caratteristica peculiare della musica jazz è l'improvvisazione la quale,  partendo dalla semplice variazione sul tema iniziale, ha assunto via via sempre  maggiore importanza. Nella forma che fu chiamata &quot;free jazz&quot; e che  ebbe il suo periodo d'oro negli anni sessanta-settanta, il tema poteva anche  scomparire in esperimenti che venivano chiamati &quot;improvvisazione totale  collettiva&quot;.<br>
  La formazione jazzistica moderna tipica è costituita da un gruppo musicale  di dimensioni limitate. La combinazione più frequente è il quartetto, quasi  invariabilmente costituito da una sezione ritmica composta da batteria, basso o  contrabbasso, pianoforte e da uno strumento solista, generalmente un sassofono  o una tromba.<br>
  Nell'ambito della piccola formazione sono possibili e frequenti una gran  varietà di cambiamenti. Per quello che riguarda la consistenza numerica, si  trovano esempi di performance solistiche (spesso, ma non sempre, si tratta di  pianoforte solo) fino ad arrivare al nonetto, formazione che comincia già ad  assumere caratteristiche orchestrali. Si hanno anche svariatissime combinazioni  per quello che riguarda la qualità degli strumenti coinvolti: si hanno esempi  di jazz suonato solisticamente con la maggior parte degli strumenti orchestrali  (perfino oboe e arpa) o folcloristici (ad esempio, la kora).<br>
  Il jazz possiede anche una lunga tradizione orchestrale, che ha avuto come  protagonisti musicisti d'eccezione. Le formazioni jazzistiche orchestrali, che  entrarono in crisi profonda alla fine degli anni trenta, sono oggi abbastanza  rare, soprattutto a causa delle difficoltà economiche e organizzative collegate  alla gestione di un complesso che comprende molte decine di musicisti.<br>
  Per lungo tempo il territorio privilegiato dai musicisti afroamericani fu  gli Stati Uniti d'America. Il jazz è oggi suonato, composto e ascoltato in  tutto il mondo come una nuova musica colta: se questo è vero soprattutto nel  mondo occidentale, è anche vero che le esplorazioni delle radici musicali  africane che molti jazzisti intrapresero a partire dagli anni sessanta e i  contatti tra culture e stili musicali caratteristici dell'ultima parte del XX  secolo, hanno contribuito a creare molti tipi di jazz, che vanno dalla  tradizionale performance per piccolo ensemble, derivato dalle esperienze  boppistiche e post-boppistiche, alla creazione di sonorità insolite che nascono  dalla ibridazione di diverse tradizioni strumentali e musicali fino ad arrivare  a dissolversi nel genere chiamato world music (e in questo caso non si parla  più di jazz).<br>
  Un fenomeno simile ha recentemente conferito la categoria di genere colto  anche a parte della musica brasiliana e argentina (Antonio Carlos Jobim, Astor  Piazzolla e altri), che fra l'altro si è apparentata con il jazz, anche per  l'opera svolta da Stan Getz ed altri in conseguenza della quale molti standard  jazz utilizzano modelli brasiliani e argentini.</p>
