<p>Il post-punk è un movimento musicale nato verso la fine  degli anni settanta, che fonde il punk rock con elementi sperimentali  provenienti da artisti come Roxy Music e David Bowie e da generi come disco,  dub e krautrock. Esso non è da intendere come un genere musicale vero e  proprio, ma piuttosto come un'etichetta utilizzata per quei gruppi che intorno  al 1980 iniziarono ad unire il punk rock con vari altri generi musicali.</p><br>

  
<h2>Origine del termine</h2>
<p>Il termine post-punk iniziò ad essere utilizzato attorno al  1980. Forse il primo critico ad usare questo nome fu Greil Marcus il 24 luglio  1980 su Rolling Stone, in cui parlava della avanguardia post-punk pop inglese,  riferendosi a Gang of Four, The Raincoats e Essential Logic, illuminati da una  tensione, uno humour e un senso del paradosso decisamente unici nella musica  pop odierna.</p><br>

<h2>Storia</h2>
<h3>Lo sviluppo del genere</h3>
<p>Tra i gruppi che hanno dato il via a questo movimento sono  sicuramente da citare Wire, Siouxsie and the Banshees, The Falle Public Image  Ltd., la cui attività causerà la nascita di molti dei generi derivati dal  movimento. In particolare i PIL con la loro musica cupa e decadente  influenzarono il successivo movimento gothic rock  capitanato da Joy Division, Bauhaus, The  Cure, Sisters of Mercy e Killing Joke.<br>
Un altro sottogenere derivato dal post-punk fu il punk funk,  fenomeno, al contrario del gothic, concentrato soprattutto negli USA e in  particolare a New York. Questa corrente, che ebbe come capostipiti James White  and the Contortions e Buy, si sviluppò a partire dal 1981, anno in cui i Bush  Tetras pubblicarono Rituals  su 99  Records, produttrice anche di altri due seminali gruppi punk-funk come Liquid  Liquid e Esg. I precursori assoluti di questo genere sono tuttavia considerati  i Talking Heads, che già dal 1977 con l'album di debutto Talking Heads: 77  avevano posto le basi per la fusione tra punk e funk, sviluppandola in seguito  in Remain in Light. Parallelamente il punk-funk si sviluppò anche in  Inghilterra, grazie a Metal Box dei PIL, a To Each... degli A Certain Ratio e  soprattutto al debutto dei Gang of Four Entertainment!, che continuerà ad  esercitare la sua influenza fino al post-hardcore e al funk metal dei Rage  Against the Machine. Un gruppo che si colloca in parte fuori da questa  corrente, pur appartenendovi in alcuni aspetti sono i The Pop Group, che in Y  unirono al punk-funk elementi di dub, jazz e musica classica.</p><br>


<h3>Il revival</h3>
<p>Il post-punk revival è una corrente di rock alternativo nata  negli anni 2000 dove le band riprendono gli elementi del genere originale  dell'inizio degli anni ottanta. Il movimento è assai diffuso nei paesi  anglosassoni quali il Regno Unito e gli Stati Uniti e in diversi paesi del  continente europeo, ed è molto legato alla scena post-punk di Londra e di New  York degli anni ottanta.<br>
Il termine post-punk revival fu coniato da vari critici  musicali per indicare band come The Killers, The Rapture, Interpol, Franz  Ferdinand e The Strokes. Questa seconda ondata di gruppi che riprendono il  post-punk inseriscono all'interno della loro musica elementi dell'indie rock e  della dance degli ultimi anni ottanta più o meno come succedeva per il  post-punk che fondeva elementi del krautrock e della musica da discoteca della  fine degli anni settanta.</p>
